name: Java CI with Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          # Eclipse Temurin: https://github.com/actions/setup-java#supported-version-syntax
          distribution: "temurin"
      - name: Run Unit Test
        # https://github.com/gradle/gradle-build-action
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
